// This file was generated by go generate; DO NOT EDIT

package yyflag

const reStr = `^(?:(?P<rel>([+-]\d{1,5}))|(?P<jjj>(\d{3}))|(?P<yjjj>(\d)-(\d{3}))|(?P<yyjjj>(\d\d)-(\d{3}))|(?P<yyyjjj>(\d{3})-(\d{3}))|(?P<yyyyjjj>(\d{4})-(\d{3}))|(?P<dd>(\d\d))|(?P<mmdd>(\d\d)-(\d\d))|(?P<ymmdd>(\d)-(\d\d)-(\d\d))|(?P<yymmdd>(\d\d)-(\d\d)-(\d\d))|(?P<yyymmdd>(\d{3})-(\d\d)-(\d\d))|(?P<yyyymmdd>(\d{4})-(\d\d)-(\d\d))|(?P<mm>m(\d\d))|(?P<ymm>y(\d)-(\d\d))|(?P<yymm>y(\d\d)-(\d\d))|(?P<yyymm>y(\d{3})-(\d\d))|(?P<yyyymm>y(\d{4})-(\d\d))|(?P<y>y(\d))|(?P<yy>y(\d\d))|(?P<yyy>y(\d{3}))|(?P<yyyy>y(\d{4}))|.{0})(?:[T#]((?P<hhmmssf>(\d\d):(\d\d):(\d\d)\.(\d+))|(?P<hhmmss>(\d\d):(\d\d):(\d\d))|(?P<hhmm>(\d\d):(\d\d))|(?P<hh>(\d\d)))|.{0})(?:@((?P<tzn>([+-]\d\d):{0,1}(\d\d))|(?P<tzs>(.{1,50})))|.{0})$`
